# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - release
  - devel
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org