---
title: "Fitting ROC-guided survival forest in `rocTree` package"
author: Sy Han (Steven) Chiou
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    toc: true
    toc_depth: 2
    toc_float: true
bibliography: ../inst/bib/tree.bib
vignette: >
  %\VignetteIndexEntry{Fitting semiparametric regression model to recurrent event data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}{inputenc}
---

```{r default, include = FALSE}
knitr::opts_chunk$set(prompt = TRUE, comment = "", collapse = TRUE)
```	
In this vignette, we demonstrate how to use the `rocForest` function in __`rocTree`__ package
to fit the proposed Receiver Operating Characteristic (ROC) guided survival tree.

## Simulated data

We will demonstrate the usage of `rocForest` function with a simulated data prepared by the [`simu`](https://www.sychiou.com/rocTree/articles/rocTree-sim.html) function.
```{R load}
library(rocTree)
set.seed(2019)
dat <- simu(n = 100, cen = 0.25, sce = 2.1, summary = TRUE)
```

## The `rocForest` function


The complete list of arguments in `rocForest` are as follow:
```{R rocForest-arg}
args(rocForest)
```

The arguments are as follows:

* `formula` is a formula object, with the response on the left of a `~` operator, and the predictors on the right. The response must be a survival object returned by the function `Surv` from the `survival` package. 
* `data` is an optional data frame to interpret the variables occurring in the `formula`.
* `id` an optional vector used to identify the longitudinal observations of subject's id. The length of `id` should be the same as the total number of observations. If `id` is missing, then each row of `data` represents a distinct observation from subjects and all covariates are treated as a baseline covariate. 
* `subset` an optional vector specifying a subset of observations to be used in the fitting process.
* `splitBy` a character string specifying the splitting algorithm. The available options are `CON` and `dCON` corresponding to the splitting algorithm based on the total concordance measure or the difference in concordance measure, respectively. The default value is `dCON`.
* `control` a list of control parameters. 

## The `control` options

Some of the options in `control` are shared with that for `rocTree`.
The argument `control` defaults to a list with the following values:

* `tau` is the maximum follow-up time; default value is the 90th percentile of the unique observed survival times. 
* `M` is the maximum node number allowed to be in the tree; the default value is `1000`.
* `hN` is the smoothing parameter used in the Kernel; the default value is `tau / 20`.
* `minsp` is the minimum number of failure required in a node after a split; the default value is `20`. 
* `minsp2` is the minimum number of failure required in a terminal node after a split; the default value is `5`.
* `disc` is a logical vector specifying whether the covariates in `formula` are discrete (`1`). The length of `disc` should be the same as the number of covariates in `formula`.
* `parallel` is a logical vector specifying whether parallel computing will be applied to grow the random forest; the default value is `FALSE`. 
* `parCluster` is an integer value specifying the number of CPU cores to be used when `parallel = TRUE`. The default value is half of the number of CPU cores detected. 
* `B` is the number of survival trees to grow for the random forest; the default value is `500`.
* `fsz` is a `function` or a numerical value to specify the size of subsample. The default value is half of the number of subjects, e.g., `round(n) / 2`, where `n` is the number of subjects.


## Growing a Random Forest

We first load the `survival` package to enable `Surv`.
The fully grown (unpruned) time-invariant survival tree can be constructed as follow:
```{R tree}
library(survival)
fit <- rocForest(Surv(Time, death) ~ z1 + z2, id = id, data = dat)
```
